model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k
  num_classes:
  stage: 'first'
  checkpoint: epoch1

dataloaders:
  train_batch_size: 2
  valid_batch_size: 2
  num_workers: 4 

img_size: 336

plot_style: 2