model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k
  num_classes:
  stage: 'first'
  checkpoint: swa

dataloaders:
  train_batch_size: 120
  valid_batch_size: 120
  num_workers: 4 

img_size: 128

plot_style: 2

return_results: True