model:
  backbone: timm_tf_efficientnet_b5.ns_jft_in1k
  ckpt_pretrained: 
  num_classes: # in the first stage of training we don't need num_classes, since we don't have a FC head

train:
  n_epochs: &epochs 20
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  ema: True # optional, but I recommend it, since the training might get unstable otherwise
  ema_decay_per_epoch: 0.4 # 0.3 for middle/big datasets. Increase, if you have low amount of samples
  target_metric: precision_at_1
  stage: first # first = Supcon, second = FC finetuning for classification

dataloaders:
  train_batch_size: 50 # 100 ~~ 70GB GPU memory 
  valid_batch_size: 50
  num_workers: 4 # adjust this depending on your CPU cores

optimizer:
  name: SGD
  params:
    lr: 0.003 

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: *epochs
    eta_min: 0.0003 # Make sure it is smaller than lr

criterion:
  name: 'SupCon'
  params:
    temperature: 0.1

img_size: &size 336

augmentations:
  sample_save: True # Whether to save a sample of augmented images
  sample_n: 10 # Number of augmented image samples per class to save
  sample_seed: 42 # Seed for random sample
  transforms: 
    - RandomResizedCrop:
        height: *size
        width: *size 
        scale:  !!python/tuple [0.7,1]
    - Flip:
    - RandomRotate90:
    - MedianBlur:
        blur_limit: 3
        p: 0.3
    - ShiftScaleRotate:
        p: 0.4
    - OpticalDistortion:
    - GridDistortion:
    - HueSaturationValue:
